import ollama

class ResearchAgent:
    def run(self, problem):
        # We define the role so the AI knows exactly how to act
        prompt = f"""
        You are an expert Innovation Researcher. 
        Analyze the following problem: '{problem}'.
        Provide a structured, professional report containing:
        1. Root Causes
        2. Existing Technological Solutions
        3. Major Challenges
        """
        
        # This calls your local Qwen3 model
        response = ollama.chat(model='qwen3:4b', messages=[
            {'role': 'user', 'content': prompt},
        ])
        
        # Return only the text generated by the AI
        return response['message']['content']